Secrets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^secrets', include('apps.secret.urls', namespace='secret')),
    url(r'^', include('apps.login.urls', namespace='login')),
]

apps/login/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^process$', views.process, name='process'),
    url(r'^login$', views.login, name="login"),
    url(r'^logout$', views.logout, name='logout')
]

apps/secret/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.secret, name='index'),
    url(r'^/create$', views.create, name='create'),
    url(r'^/popular$', views.popular, name='popular'),
    url(r'^/delete/(?P<s_id>\d+)$', views.delete, name='delete'),
    url(r'^/like/(?P<s_id>\d+)$', views.like, name='like'),

]

apps/login/models.py
from __future__ import unicode_literals
from django.contrib import messages
import re
import bcrypt
from django.db import models

# Create your models here.
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class User(models.Model):
     fname=models.CharField(max_length=15)
     lname=models.CharField(max_length=15)
     email=models.CharField(max_length=40)
     pass_hash=models.CharField(max_length=255)
     created_at=models.DateTimeField(auto_now_add=True)
     updated_at=models.DateTimeField(auto_now=True)

class UserManager(models.Manager):
    def validEmail(self,postData):
        if len(postData) <1:
            return False
        if not EMAIL_REGEX.match(postData):
            return False
        return True
    def existingEmail(self, postData):
        if User.objects.filter(email=postData):
            return False
        else:
            return True
    def passCheck(self, postEmail, postPass):
        user=User.objects.get(email=postEmail)
        passhash=user.pass_hash
        if bcrypt.checkpw(postPass, passhash):
            return True

    def lengthCheck(self, postfname, postlname,postemail,postpass1):
        if len(postfname) < 1:
            return False
        if len(postlname) < 1:
            return False
        if len(postpass1) < 1:
            return False
        if len(postemail) < 1:
            return False
        return True
    def addUser(self, postfname, postlname, postemail,postpass):
        newhash=bcrypt.hashpw(postpass, bcrypt.gensalt())
        User.objects.create(fname=postfname,lname=postlname,email=postemail,pass_hash=newhash)
        return True

userManager=UserManager()

apps/secret/models.py
from __future__ import unicode_literals
from ..login.models import User
from django.db import models


# Create your models here.
class SecretManager(models.Manager):
    def addSecret(self, form_data):
        text=Secrets.objects.create(text=form_data['secret'], author=User.objects.get(id=form_data['author']))
        return True
    def deleteSecret(self, s_id):
        Secrets.objects.get(id=s_id).delete()
        return True
    def addLike(self, user_id, s_id):
        secret=self.get(id=s_id)
        user=User.objects.get(id=user_id)
        secret.likes.add(user)
        secret.save()
        return True

class Secrets(models.Model):
    text=models.CharField(max_length=100)
    likes=models.ManyToManyField('login.User', related_name="secrets")
    author=models.ForeignKey('login.User', related_name='secret_author')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects=SecretManager()

apps/login/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User, userManager
# Create your views here.
def index(request):
    return render(request, 'login/index.html')

def process(request):
    error=0
    if not userManager.lengthCheck(request.POST['fname'],request.POST['lname'],request.POST['email'], request.POST['pass1']):
        messages.error(request, 'Please fill out all fields.')
        error=1
    if not userManager.validEmail(request.POST['email']):
        messages.error(request, 'Email address is invalid.')
        error=1
    if not userManager.existingEmail(request.POST['email']):
        messages.error(request, 'Email address already exists.')
        error=1
    if not len(request.POST['pass1'])>7:
        messages.error(request,'Password must be at least 8 characters')
        error=1
    if not request.POST['pass1'] == request.POST['pass2']:
        messages.error(request, 'Passwords must match')
        error=1
    if error:
        return redirect('/')
    userManager.addUser(str(request.POST['fname']),str(request.POST['lname']),str(request.POST['email']),str(request.POST['pass1']))
    # messages.add_message(request, messages.SUCCESS, 'Successfully registered!')
    user=User.objects.get(email=str(request.POST['email']))
    request.session['id']=user.pk
    return redirect(reverse('secret:index'))

def login(request):
    error=0
    if not userManager.validEmail(str(request.POST['email'])):
        messages.error(request,'A valid email is required.')
        error=1
    if userManager.existingEmail(str(request.POST['email'])):
        messages.add_message(request, messages.ERROR, 'Email or password is incorrect.')
        error=1
    if error:
        return redirect('/')
    if not userManager.passCheck(request.POST['email'],request.POST['pass']):
        messages.add_message(request, messages.ERROR, 'Email or password is incorrect.')
        error=1
    if error:
        return redirect('/')
    else:
        user=User.objects.get(email=request.POST['email'])
        request.session['id']=user.pk
        # messages.add_message(request, messages.SUCCESS, 'Successfully logged in!')
        return redirect(reverse('secret:index'))


def logout(request):
    request.session.clear()
    return redirect(reverse('login:index'))

apps/secret/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.db.models import Count
from django.http import HttpResponseRedirect
from .models import Secrets
from ..login.models import User

def secret(request):
    if 'id' not in request.session:
        messages.error(request, 'Please log in to continue.')
        return redirect(reverse('login:index'))
    context={
        'data':User.objects.filter(id=request.session['id'])[0],
        'secrets':Secrets.objects.annotate(tot_likes=Count('likes')).order_by('-created_at')[:5],
    }
    return render(request, 'secret/recent.html', context)

def create(request):
    if request.method=='POST':
        Secrets.objects.addSecret(request.POST)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))
    else:
        return redirect(reverse('secret:index'))

def delete(request, s_id):
    Secrets.objects.deleteSecret(s_id)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))

def like(request, s_id):
    if 'id' not in request.session:
        messages.error(request, 'Please log in to continue.')
        return redirect(reverse('login:index'))
    Secrets.objects.addLike(request.session['id'],s_id)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))


def popular(request):
    if 'id' not in request.session:
        messages.error(request, 'Please log in to continue ')
        return redirect(reverse('login:index'))
    context={
        'data':User.objects.filter(id=request.session['id'])[0],
        'secrets':Secrets.objects.annotate(tot_likes=Count('likes')).order_by('-tot_likes'),
    }
    return render(request, 'secret/popular.html', context)

apps/login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load staticfiles %}
  <link rel="stylesheet" type='text/css' href="{% static 'login/css/style.css' %}">
</head>
<div id="login">
<h1>Login n Reg</h1>
<form action="{% url 'login:process' %}" method='post'>
  <ul>
    <li>First Name: <input type="text" name="fname"></li>
    <li>Last Name: <input type="text" name="lname"></li>
    <li>Email: <input type="text" name="email"></li>
    <li>Password: <input type="password" name="pass1"></li>
    <li>Confirm Password: <input type="password" name="pass2"></li>
    {% csrf_token %}
    <li><input type="submit" value="Register"></li>
  </ul>
</form>
<form action="{% url 'login:login' %}" method='post'>
<h1>Login</h1>
  <ul>
    <li>Email: <input type="text" name='email'></li>
    <li>Password: <input type="password" name="pass"></li>
    {% csrf_token %}
    <li><input type="submit" value='Login'></li>
  </ul>
</form>
</div>
<div id="alert">
  {%if messages %}
  <ul class="messages">
    {% for message in messages %}
    {% if message.tags %}
    <li class="{{message.tags}}">{{message}}</li>
    {%else%}
    <li>{{message}}</li>
    {% endif %}
    {% endfor %}
  </ul>
  {% endif %}
</div>

apps/login/templates/login/result.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load staticfiles %}
  <link rel="stylesheet" type='text/css' href="{% static 'login/css/style.css' %}">
  <title>Login n Reg | Success</title>
</head>
<body>

  <h1>Success! Welcome, {{data.fname}}</h1>

  {%if messages %}
  <ul class="messages">
    {% for message in messages %}
    {% if message.tags %}
    <li class="{{message.tags}}">{{message}}</li>
    {%else%}
    <li>{{message}}</li>
    {% endif %}
    {% endfor %}
  </ul>
  {% endif %}
  <a href="{% url 'login:logout' %}"><button>Log Out</button></a>

  {% if all %}
  <ul>
    {% for items in all %}
    <li>{{items.pk}} {{items.fname}} {{items.lname}} - {{items.email}} - {{items.created_at}}</li>
    {% endfor %}
  {%else%}
  <li>Nothing yet</li>
  {% endif %}
  </ul>
</body>
</html>

apps/secret/templates/secret/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load staticfiles %}
  <link rel="stylesheet" type='text/css' href="{% static 'secret/css/style.css' %}">
  <title>Login n Reg | Success</title>
</head>
<body>
  <h1>Welcome, {{data.fname}}</h1>
  <form action="{% url 'secret:create' %}" method='post'>
  {% csrf_token %}
  <textarea name="secret" rows="4" cols="40"></textarea>
  <input type="hidden" name='author' value='{{data.id}}'>
  <input type="submit" value='Post'>
</form>
<h2>{%block title%}{% endblock %}</h2>
<div id="content">
  {% block content %}{% endblock %}
</div>
<a href="{% url 'login:logout' %}"><button>Log Out</button></a>

apps/secret/templates/secret/popular.html
{% extends 'secret/index.html' %}

{% block title %}Popular Secrets{% endblock %}

{%block content %}
<ul>
  {% for items in secrets %}
  <li>{{items.text}} ({{items.created_at|timesince}}) {{items.tot_likes}} likes
    {% if not items.author.id == request.session.id %}
    {% if data in items.likes.all %}
    <span>You liked this</span>
    {% else %}
    <a href="{% url 'secret:like' s_id=items.id %}">Like</a>
    {% endif %}
    {% endif %}
    {% if items.author.id == request.session.id %}
    You posted this. <a href="{% url 'secret:delete' s_id=items.id %}">Delete</a>
    {%endif%}
  </li>
  {% endfor %}
</ul>
<a href="{% url 'secret:index'%}">Recent Secrets</a>
{% endblock %}

apps/secret/templates/secret/recent.html
{% extends 'secret/index.html' %}

{% block title %}Recent secrets{% endblock %}

{%block content %}
<ul>
  {% for items in secrets %}
  <li>{{items.text}} ({{items.created_at|timesince}}) {{items.tot_likes}} likes
    {% if not items.author.id == request.session.id %}
    {% if data in items.likes.all %}
    <span>You liked this</span>
    {% else %}
    <a href="{% url 'secret:like' s_id=items.id %}">Like</a>
    {% endif %}
    {% endif %}    
    {% if items.author.id == request.session.id %}
    You posted this. <a href="{% url 'secret:delete' s_id=items.id %}">Delete</a>
    {%endif%}
  </li>
  {% endfor %}
</ul>
<a href="{% url 'secret:popular'%}">View Popular Secrets</a>
{% endblock %}